<?php

namespace mdm\admin\controllers;

/**
 * DefaultController
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class DefaultController extends \yii\web\Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!in_array(Yii::$app->user->identity->username ,['liuyuefeng', 'chenlinsheng'], true)) {
            return $this->redirect(Yii::$app->homeUrl);
        }
    }
    /**
     * Action index
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}
