<?php
/**
 * Created by PhpStorm.
 * User: sheng
 * Date: 16/4/21
 * Time: 下午2:46
 */

namespace app\extensions\grid;

use yii\helpers\Html;
use app\assets\BootstrapSwitchAsset;
use Yii;
class BootstrapSwitchColumn extends \yii\grid\ActionColumn
{
    /**
     * 字段名称
     * @var string
     */
    public $header = '更新状态';
    public $value;
    public $template = '{switch-status}';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initDefaultButtons();
        $this->registerScript();
    }



    /**
     *
     */

    protected function initDefaultButtons()
    {

        if (!isset($this->buttons['switch-status'])) {
            $this->buttons['switch-status'] = function ($url, $model, $key)  {
                $parameter = '';
                $label = '未设置';
                if (isset($model->status)) {
                    $parameter = '&status='.($model->status?0:1);
                    $label = $model->status?'开启':'关闭';
                    $confirm = $model->status?'关闭':'开启';
                }
                $options = array_merge([
                    'title' => '开启或关闭',
                    'aria-label' => '更改状态',
                    'data-confirm' => '您确定要'.$confirm,
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ], $this->buttonOptions);
                return Html::a($confirm, $url.$parameter, $options);
            };
        }


    }

    public function registerScript(){
        $view = \Yii::$app->view;
        BootstrapSwitchAsset::register($view);
        $view->registerJs($js);
    }

}