<?php
namespace app\extensions\grid;
/**
 * Created by PhpStorm.
 * User: i-sheng
 * Date: 15-11-20
 * Time: 下午6:39
 */
use Yii;
use yii\bootstrap\Modal;
use yii\helpers\Html;
class HodoActionColumn extends \yii\grid\ActionColumn{
    public $header = '操作';
    public $template ='{view} {update} {delete} {switch-status}'; // {delete}
    /**
     * modal title text
     */
    public $modalTitle ;
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initDefaultButtons();
        $this->registerJs();
    }

    protected function registerJs(){
        $js = <<<JS
        $('.activity-view-link').each(function(index) {
            $(this).click(function(e) {
                url = $(this).attr('data-url');
                $('#hodoactivity-modal').modal();
                $.get(
                    url,
                    function (data) {
                        $('#hodoactivity-modal').find('.modal-body').html(data);
                        $('#hodoactivity-modal').modal();
                    }
                );
            });
        });
JS;
        Yii::$app->view->registerJs($js);

        Modal::begin([
            'id' => 'hodoactivity-modal',
            'header' => '<h6 class="modal-title"></h6>',
            'footer' => '<a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>',
        ]);
        Modal::end();

    }

    protected function initDefaultButtons()
    {
        if (!isset($this->buttons['view'])) {
            $this->buttons['view'] = function ($url, $model, $key) {
                $options = array_merge([
                    'class' => 'activity-view-link',
                    'title' => Yii::t('yii', 'View'),
                    'aria-label' => Yii::t('yii', 'View'),
                    'data-pjax' => '0',
                    'data-toggle' => 'modal',
                    //'data-target' => '#hodoactivity-modal',
                    'data-url' => $url
                ], $this->buttonOptions);
                return Html::a('查看', 'javascript:void(1)', $options);
            };
        }
        if (!isset($this->buttons['update'])) {
            $this->buttons['update'] = function ($url, $model, $key) {
                $options = array_merge([
                    'title' => Yii::t('yii', 'Update'),
                    'aria-label' => Yii::t('yii', 'Update'),
                    'data-pjax' => '0',
                ], $this->buttonOptions);
                return Html::a('编辑', $url, $options);
            };
        }
        if (!isset($this->buttons['delete'])) {
            $this->buttons['delete'] = function ($url, $model, $key) {
                $options = array_merge([
                    'title' => Yii::t('yii', 'Delete'),
                    'aria-label' => Yii::t('yii', 'Delete'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ], $this->buttonOptions);
                return Html::a('删除', $url, $options);
            };
        }
        if (!isset($this->buttons['switch-status'])) {
            $this->buttons['switch-status'] = function ($url, $model, $key)  {
                $parameter = '';
                $label = '未设置';
                $strategy_id = Yii::$app->request->getQueryParam('strategy_id');
                if(!empty($strategy_id)){
                    $parameter .= '&strategy_id='. $strategy_id;
                }
                if (isset($model->status)) {
                    $parameter .= '&status='.($model->status?0:1);
                    $confirm = $model->status?'关闭':'开启';
                }
                $options = array_merge([
                    'title' => '开启或关闭',
                    'aria-label' => '更改状态',
                    'data-confirm' => '您确定要'.$confirm,
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ], $this->buttonOptions);
                return Html::a($confirm, $url.$parameter, $options);
            };
        }

    }
}