<?php
/**
 * Created by PhpStorm.
 * User: i-sheng
 * Date: 15-11-23
 * Time: 下午12:02
 */

namespace app\extensions\widget;


use yii\helpers\Html;
use yii\widgets\LinkPager;

class HodoLinkPager extends LinkPager
{
    public $promptText;
    public $pageTextFormat;
    public $htmlOptions;
    public $nextPageLabel = '下一页';
    public $prevPageLabel = '上一页';
    public $options = ['class' => 'pagination pull-right'];

    /**
     * Initializes the pager.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->htmlOptions['class'] = 'form-control';
        $this->htmlOptions['data-pjax'] = '0';
        if(!isset($this->htmlOptions['onchange']))
            $this->htmlOptions['onchange']="if(this.value!='') {window.location=this.value;};";
    }

    /**
     * Executes the widget.
     * This overrides the parent implementation by displaying the generated page buttons.
     */
    public function run()
    {

        if ($pageCount = $this->pagination->getPageCount() <= 1) return;

        $pageSize = [];
        $page = [];

        $selection = $this->pagination->createUrl($this->pagination->getPage());
        for($i=1; $i<6; ++$i){
            $size = $i * $this->maxButtonCount;
            $pageSize[$this->pagination->createUrl($this->pagination->getPage(),$size)] = $size;
        }
        list($beginPage, $endPage) = $this->getPageRange();
        for($j=$beginPage; $j<=$endPage; ++$j){
            $page[$this->pagination->createUrl($j)] = $j+1;
        }

        echo Html::tag('div',Html::tag('div', '每页条数', ['class' => 'pull-left padding-8'])
            .Html::tag('div', Html::dropDownList($this->getId().'pageSize',$selection , $pageSize, $this->htmlOptions), ['class' => 'pull-left']), ['class' => "page-select"]);
        echo '</div>';

        echo '<div class="col-md-8">';
        echo Html::tag('div',Html::tag('div', '跳转到', ['class' => 'pull-left padding-8 '])
            .Html::tag('div', Html::dropDownList($this->getId().'page',$selection , $page, $this->htmlOptions), ['class' => "page-select"]), ['class' => 'pull-right']);

        parent::run(); // TODO: Change the autogenerated stub
        echo '</div>';
    }


}