<?php

namespace app\models;

use Yii;
use app\components\HodoActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\TimestampBehavior;
use yii\caching\DbDependency;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "admin_user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $app_id
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $channels
 */
class AdminUser extends HodoActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    /*渠道列表*/
    public $channels;

    /**
     * 是不是另一个渠道账号
     */
    public $provider;
    /**
     * @var string 分配的的权限
     */
    public $role;
    /**
     * @return array
     * @throws \Exception
     */
    public static function getDataList(){
        $db = Yii::$app->db;// or Category::getDb()
        $dep = new DbDependency();
        $dep->sql = 'SELECT count(*) FROM '.self::tableName();
        $result = $db->cache(function ($db) {
            return self::find()
                ->select('`id`, `username`')
                ->orderBy('id desc')
                ->asArray()
                ->all();
        }, 1500, $dep);
        $arr =  ArrayHelper::map($result, 'id', 'username');
        return $arr;
    }

    /**
     * @return array
     * @throws \Exception
     * @var $db \yii\db\Connection
     */
    public static function getRoleList(){
        $db = Yii::$app->db;// or Category::getDb()
        $dep = new DbDependency();
        $dep->sql = 'SELECT count(*) FROM auth_assignment';

        $result = $db->cache(function ($db) {
            return $db->createCommand('SELECT * FROM auth_item WHERE type=1')->queryAll();
        }, 1500, $dep);
        $arr =  ArrayHelper::map($result, 'name', 'description');
        return $arr;
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        /**
         * 判断11是为了区别第三方的后台 http://coop.xiaolu123.com/index.php?r=coop-income%2Findex
         */
        if($this->provider){
            $this->status = 11;
        }
        $this->setPassword($this->password_hash);
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id'=>$id, 'status'=> self::STATUS_ACTIVE]);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {

    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }


    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'admin_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'created_at', 'updated_at', 'provider'], 'integer'],
            [['username', 'password_hash', 'status'], 'required'],
            [['email',], 'email'],
            [['username','email'], 'unique'],
            [['username', 'password_hash', 'password_reset_token', 'email', 'app_id'], 'string', 'max' => 255],
            [['role'], 'string', 'max' => 64],
            [['auth_key'], 'string', 'max' => 32],
            [['channels'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '账号',
            'auth_key' => '校验 Key',
            'password_hash' => '密码',
            'password_reset_token' => 'Password Reset Token',
            'email' => '邮箱',
            'role' => '角色名称',
            'app_id' => 'App ID',
            'status' => '状态',
            'channels' => '渠道',
            'created_at' => '日期',
            'provider' => '渠道方',
            'updated_at' => 'Updated At',
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
            ],
        ];
    }
}
